:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\Domivice.Users
dotnet build src\Domivice.Users
echo Now, run the following to start the project: dotnet run -p src\Domivice.Users\Domivice.Users.csproj --launch-profile web.
echo.
