/*
 * Users API
 *
 * The users API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Domivice.Users.Web.Models;

/// <summary>
///     Carries information about the user
/// </summary>
[DataContract]
public class UserUpdate : IEquatable<UserUpdate>
{
    /// <summary>
    ///     The user first name
    /// </summary>
    /// <value>The user first name</value>
    [DataMember(Name = "firstName", EmitDefaultValue = false)]
    public string FirstName { get; set; }

    /// <summary>
    ///     The user last name
    /// </summary>
    /// <value>The user last name</value>
    [DataMember(Name = "lastName", EmitDefaultValue = false)]
    public string LastName { get; set; }

    /// <summary>
    ///     The user phone number
    /// </summary>
    /// <value>The user phone number</value>
    [DataMember(Name = "phoneNumber", EmitDefaultValue = false)]
    public string PhoneNumber { get; set; }

    /// <summary>
    ///     The user phone country code
    /// </summary>
    /// <value>The user phone country code</value>
    [DataMember(Name = "phoneCountryCode", EmitDefaultValue = false)]
    public string PhoneCountryCode { get; set; }

    /// <summary>
    ///     Returns true if UserUpdate instances are equal
    /// </summary>
    /// <param name="other">Instance of UserUpdate to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(UserUpdate other)
    {
        if (other is null) return false;
        if (ReferenceEquals(this, other)) return true;

        return
            (
                FirstName == other.FirstName ||
                (FirstName != null &&
                 FirstName.Equals(other.FirstName))
            ) &&
            (
                LastName == other.LastName ||
                (LastName != null &&
                 LastName.Equals(other.LastName))
            ) &&
            (
                PhoneNumber == other.PhoneNumber ||
                (PhoneNumber != null &&
                 PhoneNumber.Equals(other.PhoneNumber))
            ) &&
            (
                PhoneCountryCode == other.PhoneCountryCode ||
                (PhoneCountryCode != null &&
                 PhoneCountryCode.Equals(other.PhoneCountryCode))
            );
    }

    /// <summary>
    ///     Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class UserUpdate {\n");
        sb.Append("  FirstName: ").Append(FirstName).Append("\n");
        sb.Append("  LastName: ").Append(LastName).Append("\n");
        sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
        sb.Append("  PhoneCountryCode: ").Append(PhoneCountryCode).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    ///     Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///     Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
        if (obj is null) return false;
        if (ReferenceEquals(this, obj)) return true;
        return obj.GetType() == GetType() && Equals((UserUpdate)obj);
    }

    /// <summary>
    ///     Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            // Suitable nullity checks etc, of course :)
            if (FirstName != null)
                hashCode = hashCode * 59 + FirstName.GetHashCode();
            if (LastName != null)
                hashCode = hashCode * 59 + LastName.GetHashCode();
            if (PhoneNumber != null)
                hashCode = hashCode * 59 + PhoneNumber.GetHashCode();
            if (PhoneCountryCode != null)
                hashCode = hashCode * 59 + PhoneCountryCode.GetHashCode();
            return hashCode;
        }
    }

    #region Operators

#pragma warning disable 1591

    public static bool operator ==(UserUpdate left, UserUpdate right)
    {
        return Equals(left, right);
    }

    public static bool operator !=(UserUpdate left, UserUpdate right)
    {
        return !Equals(left, right);
    }

#pragma warning restore 1591

    #endregion Operators
}